//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerEarlyClaim.FalcoRib {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FalcoRib.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendMail", ReplyAction="http://tempuri.org/IService/SendMailResponse")]
        string SendMail(string fromname, string subject, string from, string replytoid, string[] recipients, string[] recipientsCC, string Bcc, string content, string[] filename, string[] filecontent, string[] attributes, string[] apiHeader, string tags, string template, string otherAttributes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendMail", ReplyAction="http://tempuri.org/IService/SendMailResponse")]
        System.Threading.Tasks.Task<string> SendMailAsync(string fromname, string subject, string from, string replytoid, string[] recipients, string[] recipientsCC, string Bcc, string content, string[] filename, string[] filecontent, string[] attributes, string[] apiHeader, string tags, string template, string otherAttributes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SchedulerEarlyClaim.FalcoRib.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SchedulerEarlyClaim.FalcoRib.IService>, SchedulerEarlyClaim.FalcoRib.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMail(string fromname, string subject, string from, string replytoid, string[] recipients, string[] recipientsCC, string Bcc, string content, string[] filename, string[] filecontent, string[] attributes, string[] apiHeader, string tags, string template, string otherAttributes) {
            return base.Channel.SendMail(fromname, subject, from, replytoid, recipients, recipientsCC, Bcc, content, filename, filecontent, attributes, apiHeader, tags, template, otherAttributes);
        }
        
        public System.Threading.Tasks.Task<string> SendMailAsync(string fromname, string subject, string from, string replytoid, string[] recipients, string[] recipientsCC, string Bcc, string content, string[] filename, string[] filecontent, string[] attributes, string[] apiHeader, string tags, string template, string otherAttributes) {
            return base.Channel.SendMailAsync(fromname, subject, from, replytoid, recipients, recipientsCC, Bcc, content, filename, filecontent, attributes, apiHeader, tags, template, otherAttributes);
        }
    }
}
